services:
  gunicorn:
    image: gunicorn
    build: ./src
    ports:
      - "8000":"8000"
  #nginx:
  #  image: nginx
  #  build: ./nginx
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  depends_on:
  #    - gunicorn
  #  volumes:
  #    - ./data/certbot/conf:/etc/letsencrypt
  #    - ./data/certbot/www:/var/www/certbot
  #ddclient:
  #  image: lscr.io/linuxserver/ddclient:latest
  #  container_name: ddclient
  #  environment:
  #    - TZ=Europe/London
  #  volumes:
  #    - ./config/ddclient:/config:ro
  #  restart: unless-stopped
  #certbot:
  #  image: certbot/certbot:arm64v8-latest
  #  volumes:
  #    - ./data/certbot/conf:/etc/letsencrypt
  #    - ./data/certbot/www:/var/www/certbot
  #  depends_on:
  #    - nginx


