services:
  gunicorn:
    image: gunicorn
    build: ./src
    expose:
      - 8000
    restart: unless-stopped
  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gunicorn
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - TZ=Europe/London
    volumes:
      - ./config/ddclient:/config:ro
    restart: unless-stopped
  certbot:
    image: certbot/certbot:arm64v8-latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
      - ddclient


